# Generated by Django 4.2.20 on 2025-03-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('start_date', models.DateField(blank=True, help_text='Укажите дату первого выполнения привычки', null=True, verbose_name='Дата первого выполнения')),
                ('start_time', models.TimeField(blank=True, help_text='Время выполнения привычки в секундах', null=True, verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('is_pleasure', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.SmallIntegerField(default=1, help_text='Укажите периодичность выполнения привычки в днях', verbose_name='Периодичность')),
                ('prize', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('action_time', models.SmallIntegerField(default=120, help_text='Укажите время на выполнение в секундах', verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Укажите приятную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_habit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['owner'],
            },
        ),
    ]
